goal=YourGoal

ic=12 # number of img clients
tc=12 # number of txt clients
mc=8 # number of img+txt clients
cncntrtn=0.5 # concentration parameter for Dirichlet distribution
c=0.25 # sampling ratio for clients
nt=8 # number of threads for parallel training
b=96 # batch size
root='' # root path of the dataset

python main.py --exp_name FedAVG --shared_param none --share_scope dataset --colearn_param none --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C $c --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 8 --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C $c --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 8 --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 
python main.py --exp_name FedIoT --shared_param blocks --share_scope modality_exact --colearn_param none --algorithm fediot --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C $c --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 8 --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 
python main.py --exp_name FedProx --shared_param none --share_scope dataset --colearn_param none --algorithm fedprox --mu 0.001 --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512
python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C $c --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 8 --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-7 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128
